# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Toggle between readme templates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install
    - run: npm run start change-readme
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add README.md
        git add -A && git commit -m "[BOT] Update Readme"
        git push origin master
        
      
